### ISSUE TITLE
Kubernetes yaml templates or Helm chart

### ISSUE THREAD

**Issue by dkirrane** [deviantony/docker-elk#209]
Wondering if you have any K8s templates or Helm chart for standing up ELK  with SearchGaurd in a Kubernetes cluster

**Comment by jemacom** [comment]
Hey @dkirrane I was about to suggest using [kompose](http://kompose.io/). But after testing it locally it fails since the  `docker-compose.yml` uses `build` and `context` and the Kompose maintainers still on it. 
Check this [issue](https://github.com/kubernetes/kompose/issues/832)

**Comment by antoineco** [comment]
I think this is way beyond the scope of this project, but here is an excellent starting point for running ELK on Kubernetes:

https://github.com/pires/kubernetes-elasticsearch-cluster

You should be able to swap the images and get it running with Searchguard without problem.

**Comment by surajnarwade** [comment]
@jemacom ,[ issue ](https://github.com/kubernetes/kompose/issues/832) is fixed now :)

**Comment by jemacom** [comment]
@surajnarwade I think am still facing some issues although am using the 1.6 release. 
```bash
$kompose version                                               
1.6.0 (e4adfef)
```
```bash
$kompose up                                                   
WARN Unsupported root level networks key - ignoring 
WARN Unsupported depends_on key - ignoring        
WARN Unsupported networks key - ignoring          
FATA Error while deploying application: k.Transform failed: image key required within build parameters in order to build and push service 'elasticsearch'
```

Any thoughts on this ? Thanks.

**Comment by surajnarwade** [comment]
@jemacom you need to mention `image` key in your services in docker compose file. then `kompose` will build your image with that name, push it to registry and then your cluster will pull it and deploy :)

**Comment by antoineco** [comment]
I'm not sure how far you managed to get with that *ELK on Kubernetes* story, but I found the following Helm charts in the Kubernetes GitHub org:

- https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch
- https://github.com/kubernetes/charts/tree/master/incubator/logstash
- https://github.com/kubernetes/charts/tree/master/stable/kibana

All 3 charts use the same Docker images as we do in this project and seem easy to configure. **In my opinion this is by far more elegant and maintainable than using Kompose.**

I suggest you give it a shot. I will close this issue in a few days because Kubernetes is a very special beast that do not share much with our Compose setup, but I welcome further discussion if you need guidance.
