### ISSUE TITLE
kibana search guard menus disabled except signal menu

### ISSUE THREAD

**Issue by ismailazerty** [deviantony/docker-elk#563]
Hello,

      I have all kibana search guard menus disabled, except signals menu. Any Idea please ?

thx

**Comment by antoineco** [comment]
This was supposed to have been fixed by #498, but maybe some extra permissions are required in more recent versions. Let me check.

**Comment by antoineco** [comment]
@ismailazerty I pushed a fix via the pull request above ☝️  I will merge it in a few minutes, as soon as the tests pass.

Thanks for reporting!

**Comment by ismailazerty** [comment]
> @ismailazerty I pushed a fix via the pull request above ☝️ I will merge it in a few minutes, as soon as the tests pass.
> 
> Thanks for reporting!

great thank you

**Comment by ismailazerty** [comment]
> @ismailazerty I pushed a fix via the pull request above ☝️ I will merge it in a few minutes, as soon as the tests pass.
> 
> Thanks for reporting!

I still can't access the config menu, is it related to search guard license ?

![image](https://user-images.githubusercontent.com/17010211/104373777-2bad6e00-5521-11eb-8739-ed95a197bbcd.png)

**Comment by antoineco** [comment]
No, the trial license gives you access to all features.

Try running `docker-compose up --build` in order to ensure the newest version of the config files is included into the local Elasticsearch image, then run `init_sg.sh` one more time to update the config index, then you should be good to go.

**Comment by ismailazerty** [comment]
Already done all those steps.
Because the Trial version is limited in time, I dont want to use it.  Is it working with basic version ?

**Comment by antoineco** [comment]
Oh I didn't get that. No, unfortunately the GUI is a paid feature: https://search-guard.com/licensing/

Under _Feature Breakdown_:

```
REST management API
Configuration GUI
```

With that being said, the menus were disabled even with a valid (trial) license, so I'm glad you raised my attention .
